AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: This template deploys Cognito Post Confirmation User Exporter Function
Parameters:
  FunctionName:
    Type: String
    Default: empty-content-cleanser-function
  StreamTableName:
    Type: String
  StreamTableIsSealedStartTimeIndex:
    Type: String
  Environment:
    Type: String
    Default: dev
  Application:
    Type: String
    Default: tafalk
Resources:
  EmptyContentCleanserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref FunctionName
      CodeUri: ./
      Handler: "lambda_function.lambda_handler"
      Environment:
        Variables:
          STREAM_TABLE_NAME: !Ref StreamTableName
          STREAM_TABLE_IS_SEALED_START_TIME_INDEX_NAME: !Ref StreamTableIsSealedStartTimeIndex
      MemorySize: 128
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "logs:*"
                - "dynamodb:*"
              Resource: "*"
      Runtime: python3.8
      Timeout: 3
      Events:
        CronEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 3 * * ? *)
            Enabled: True
      Tags:
        Environment: !Ref Environment
        Application: !Ref Application
